language: python
python:
- '2.7'
install: 
- pip install -r requirements.txt
script:
- make clean
- make release
deploy:
  provider: releases
  api_key:
    secure: LRM8ZzPgJUALKL7/ls9RvqmFoksE+Gq7+ud+l5ha+by7ptb1FWRXEjIWoELC8ieFioAi2aXKcYASKnwkIqmcwkH556mK+E4xaohdqN1jndVYxbe/Dle+cHO0G6vRjQWPJdp17sLlKKBfrt0p+JblqVf5tS3GoR5MVMeZp5/xThY=
  file_glob: true    
  file: 
    - TestFlightCore*.zip
    - TestFlightConfigRO*.zip
    - TestFlightConfigStock*.zip
  skip_cleanup: true
  on:
    repo: jwvanderbeck/TestFlight
    tags: true
    all_branches: true
notifications:
  irc:
    channels:
      - "irc.esper.net#TestFlight"
    skip_join: true
    use_notice: true
    on_success: change
    on_failure: change
    template:
      - "Build #%{build_number} - %{branch} - %{result}"
      - "%{commit_message}"
after_success:
- make deploy
env:
  global:
  - secure: KK4zCiujTh58oH6dX5Hphi357mwnDrjFS9oVbCOaDUk+Uwz6qhEUgwvWZu5a2/wEFFRV4JyRm27QsAdDAJ0qy0f+SW6yoTIrdYx3PTDuWl+CL4L5yGV6K/LYrGrtDz1AXLFupfhgPcoB62dYDmZmzCHNioB8BY5zuuA9o3fzxcU=
  - secure: fLfigVPg9ubGokcauE+797nTcw63TPjsJXmKrzG1JqsvzCXzd4qVrbw6zuwO7rRzAaimqwbxjIVxZFqzJHb9jCut3FcM+iMranewM75qRErqSZh14sImWi9YMRIl5wkb0xElGIbPYAY1aqR89V8m20CthTX21/dfmJhTa8EyAPM=
  - secure: TTeep3257heuzclYnRD5r+fKCuilW+heZynKplW30SGckkrdtcZe6lbYs0tQ+5o3a8X1y41TQHKgXIJQM0P2DIfKODT9iofpu4gCIZoL+cF7Mj3BKoBHz7zKtYoCMdP/fkTh8cJMpV5nERhiADmC4hSdghwUmydLFI2VS7IUIO0=
