# Predefined repair setups so they can be re-used later
RepairConfigs:
- &EasySoftware
    canBeRepairedByRemote: true
    canBeRepairedInFlight: true
    canBeRepairedOnSplashed: true
    dataScale: 1
    dataSize: 1
    repairChance: 75
- &MediumHydraulic
    canBeRepairedByRemote: false
    canBeRepairedInFlight: false
    canBeRepairedOnSplashed: false
    repairChance: 50
    replacementPart: 'HydraulicGizmo'
    replacementPartOptional: true
    replacementPartBonus: 0.10
- &EasyMechanical
    canBeRepairedByRemote: false
    canBeRepairedInFlight: false
    canBeRepairedOnSplashed: false
    repairChance: 75
# Predefined failure configs
FailureConfigs:
- &ShutdownEngine
    failureTitle: 'Engine Shutdown'
    failureType: 'software'
    duFail: 100
    duRepair: 50
    severity: 'failure'
- &LockGimbal
    failureTitle: 'Gimbal Failure'
    failureType: 'mechanical'
    duFail: 100
    duRepair: 250
    severity: 'failure'
- &ReducedMaxThrust
    failureTitle: 'Loss of Thrust'
    failureType: 'mechanical'
    duFail: 100
    duRepair: 250
    severity: 'failure'
- &Explode
    failureTitle: 'Explosion!'
    failureType: 'mechanical'
    duFail: 400
    severity: 'major'
- &ResourceLeak_LiquidFuel
    failureTitle: 'Liquid Fuel Leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'LiquidFuel'
    initialAmount: 10
    perSecondAmount: 1
- &ResourceLeak_Oxidizer
    failureTitle: 'Oxidizer Leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'Oxidizer'
    initialAmount: 10
    perSecondAmount: 1
- &ResourceLeak_MonoPropellant
    failureTitle: 'MonoPropellant Leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'MonoPropellant'
    initialAmount: 1
    perSecondAmount: 0.1
- &ResourceLeak_Random
    failureTitle: 'Tank is leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'random'
    initialAmount: 5
    perSecondAmount: 1
- &IgnitionFail
    failureTitle: 'Failed to ignite'
    failureType: 'mechanical'
    duFail: 300
    severity: 'major'
    oneShot: true
# We define all the details of the configs here and then reference them later when actually attaching them to parts
PartConfigs:
    WAC-Corporal: &WAC-Corporal
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
            configuration: 'engineConfig = WAC-Corporal:WAC-Corporal'
            title: 'WAC Corporal'
        -   name: 'FlightDataRecorder_Engine'
            configuration: 'WAC-Corporal'
            flightDataMultiplier: 10
            flightDataEngineerModifier: 0.25
        -   name: 'TestFlightReliability'
            configuration: 'WAC-Corporal'
            RELIABILITY_BODY:
            -   scope: 'default'
                reliabilityCurve:
                    - '0 0.024 0 0'
                    - '1000 0.0144 0 0'
                    - '4000 0.0072 0 0'
                    - '10000 0.0048 0 0'
        -   name: 'TestFlightReliability_EngineCycle'
            configuration: 'WAC-Corporal'
            ratedBurnTime: 125
            cycle:
            - '0.00 5.00 0 0'
            - '5.00 1.00 0 0'
            - '125.00 1.00 0 0'
            - '245.00 10.00 0 0'
        # When referencing a block like this for use in a module, the blocks have to come BEFORE the module itself.  They will then get folded down into it
        -   *ShutdownEngine        
        -   name: 'TestFlightFailure_ShutdownEngine'
            configuration: 'WAC-Corporal'
            weight: 16
            REPAIR:
            - *EasySoftware
        -   *IgnitionFail
        -   name: 'TestFlightFailure_IgnitionFail'
            configuration: 'WAC-Corporal'
            restoreIgnitionCharge: false
            ignitionFailureRate:
                - '0 0.05'
                - '5000 0.01'
        -   *ReducedMaxThrust
        -   name: 'TestFlightFailure_ReducedMaxThrust'
            configuration: 'WAC-Corporal'
            weight: 16
            REPAIR:
            - *EasyMechanical
        -   *Explode
        -   name: 'TestFlightFailure_Explode'
            configuration: 'WAC-Corporal'
            weight: 4
    Aerobee-Hi: &Aerobee-Hi
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
            configuration: 'engineConfig = Aerobee-Hi:Aerobee-Hi'
            title: 'Aerobee Hi'
            techTransfer: 'WAC-Corporal:50'
            techTransferMax: 2000
        -   name: 'FlightDataRecorder_Engine'
            configuration: 'Aerobee-Hi'
            flightDataMultiplier: 10
            flightDataEngineerModifier: 0.25
        -   name: 'TestFlightReliability'
            configuration: 'Aerobee-Hi'
            RELIABILITY_BODY:
            -   scope: 'default'
                reliabilityCurve:
                    - '0 0.008372 0 0'
                    - '1000 0.005023 0 0'
                    - '4000 0.002512 0 0'
                    - '10000 0.000419 0 0'
        -   name: 'TestFlightReliability_EngineCycle'
            configuration: 'Aerobee-Hi'
            ratedBurnTime: 125
            cycle:
            - '0.00 5.00 0 0'
            - '5.00 1.00 0 0'
            - '105.00 1.00 0 0'
            - '155.00 10.00 0 0'
        # When referencing a block like this for use in a module, the blocks have to come BEFORE the module itself.  They will then get folded down into it
        -   *ShutdownEngine        
        -   name: 'TestFlightFailure_ShutdownEngine'
            configuration: 'Aerobee-Hi'
            weight: 16
            REPAIR:
            - *EasySoftware
        -   *IgnitionFail
        -   name: 'TestFlightFailure_IgnitionFail'
            configuration: 'Aerobee-Hi'
            restoreIgnitionCharge: false
            ignitionFailureRate:
                - '0 0.05'
                - '5000 0.01'
        -   *ReducedMaxThrust
        -   name: 'TestFlightFailure_ReducedMaxThrust'
            configuration: 'Aerobee-Hi'
            weight: 16
            REPAIR:
            - *EasyMechanical
        -   *Explode
        -   name: 'TestFlightFailure_Explode'
            configuration: 'Aerobee-Hi'
            weight: 4
    Aerobee-150: &Aerobee-150
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
            configuration: 'engineConfig = Aerobee-150:Aerobee-150'
            title: 'Aerobee 150'
            techTransfer: 'WAC-Corporal,Aerobee-Hi:50'
            techTransferMax: 5000
        -   name: 'FlightDataRecorder_Engine'
            configuration: 'Aerobee-150'
            flightDataMultiplier: 10
            flightDataEngineerModifier: 0.25
        -   name: 'TestFlightReliability'
            configuration: 'Aerobee-150'
            RELIABILITY_BODY:
            -   scope: 'default'
                reliabilityCurve:
                    - '0 0.001036 0 0'
                    - '1000 0.000777 0 0'
                    - '3000 00.000518 0 0'
                    - '10000 0.000362 0 0'
        -   name: 'TestFlightReliability_EngineCycle'
            configuration: 'Aerobee-150'
            ratedBurnTime: 125
            cycle:
            - '0.00 5.00 0 0'
            - '5.00 1.00 0 0'
            - '105.00 1.00 0 0'
            - '155.00 10.00 0 0'
        # When referencing a block like this for use in a module, the blocks have to come BEFORE the module itself.  They will then get folded down into it
        -   *ShutdownEngine        
        -   name: 'TestFlightFailure_ShutdownEngine'
            configuration: 'Aerobee-150'
            weight: 16
            REPAIR:
            - *EasySoftware
        -   *ReducedMaxThrust
        -   name: 'TestFlightFailure_ReducedMaxThrust'
            configuration: 'Aerobee-150'
            weight: 16
            REPAIR:
            - *EasyMechanical
        -   *Explode
        -   name: 'TestFlightFailure_Explode'
            configuration: 'Aerobee-150'
            weight: 4
# And here we actually take all the stuff defined above and apply it to actual parts
Parts:
-   part: 'WAC-Corporal'
    patterns:
    - "@PART[ROAerobeeSustainer]:AFTER[RealismOverhaul]"
    configs:
    - *WAC-Corporal
    - *Aerobee-Hi
    - *Aerobee-150
