# Predefined repair setups so they can be re-used later
RepairConfigs:
- &EasySoftware
	canBeRepairedByRemote: true
	canBeRepairedInFlight: true
	canBeRepairedOnSplashed: true
	dataScale: 1
	dataSize: 1
	repairChance: 75
- &MediumHydraulic
    canBeRepairedByRemote: false
    canBeRepairedInFlight: false
    canBeRepairedOnSplashed: false
    repairChance: 50
    replacementPart: 'HydraulicGizmo'
    replacementPartOptional: true
    replacementPartBonus: 0.10
- &EasyMechanical
    canBeRepairedByRemote: false
    canBeRepairedInFlight: false
    canBeRepairedOnSplashed: false
    repairChance: 75
FailureConfigs:
- &ShutdownEngine
    failureTitle: 'Engine Shutdown'
    failureType: 'software'
    duFail: 100
    duRepair: 50
    severity: 'failure'
- &LockGimbal
    failureTitle: 'Gimbal Failure'
    failureType: 'mechanical'
    duFail: 100
    duRepair: 250
    severity: 'failure'
- &ReducedMaxThrust
    failureTitle: 'Loss of Thrust'
    failureType: 'mechanical'
    duFail: 100
    duRepair: 250
    severity: 'failure'
- &Explode
    failureTitle: 'Explosion!'
    failureType: 'mechanical'
    duFail: 400
    severity: 'major'
- &ResourceLeak_LiquidFuel
    failureTitle: 'Liquid Fuel Leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'LiquidFuel'
    initialAmount: 10
    perSecondAmount: 1
- &ResourceLeak_Oxidizer
    failureTitle: 'Oxidizer Leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'Oxidizer'
    initialAmount: 10
    perSecondAmount: 1
- &ResourceLeak_MonoPropellant
    failureTitle: 'MonoPropellant Leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'MonoPropellant'
    initialAmount: 1
    perSecondAmount: 0.1
- &ResourceLeak_Random
    failureTitle: 'Tank is leaking'
    failureType: 'mechanical'
    duFail: 25
    duRepair: 50
    severity: 'failure'
    resourceToLeak: 'random'
    initialAmount: 5
    perSecondAmount: 1
- &IgnitionFail
    failureTitle: 'Failed to ignite'
    failureType: 'mechanical'
    duFail: 300
    severity: 'major'
    oneShot: true
PartConfigs:
	# Solids
    RT5: &RT5
        # Should only ever be ONE Interop module for a unique PART in KSP.
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
        -   name: 'FlightDataRecorder_Engine'
            flightDataMultiplier: 10
            flightDataEngineerModifier: 0.25
        -   name: 'TestFlightReliability'
            reliabilityCurve:
                - '0 0.005'
                - '10000 0.002'
        # When referencing a block like this for use in a module, the blocks have to come BEFORE the module itself.  They will then get folded down into it
        -   *ReducedMaxThrust
        -   name: 'TestFlightFailure_ReducedMaxThrust'
            configuration: 'WAC-Corporal'
            weight: 32
            REPAIR:
            - *EasyMechanical
        -   *Explode
        -   name: 'TestFlightFailure_Explode'
            configuration: 'WAC-Corporal'
            weight: 8
    RT10: &RT10
        # Should only ever be ONE Interop module for a unique PART in KSP.
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
            techTransfer: 'solidBooster_sm:75'
            techTransferMax: 5000
        -   name: 'FlightDataRecorder_Engine'
            flightDataMultiplier: 5
            flightDataEngineerModifier: 0.25
        -   name: 'TestFlightReliability'
            reliabilityCurve:
                - '0 0.002'
                - '10000 0.001'
        # When referencing a block like this for use in a module, the blocks have to come BEFORE the module itself.  They will then get folded down into it
        -   *ReducedMaxThrust
        -   name: 'TestFlightFailure_ReducedMaxThrust'
            configuration: 'WAC-Corporal'
            weight: 32
            REPAIR:
            - *EasyMechanical
        -   *Explode
        -   name: 'TestFlightFailure_Explode'
            configuration: 'WAC-Corporal'
            weight: 8
    BACC: &BACC
        # Should only ever be ONE Interop module for a unique PART in KSP.
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
            techTransfer: 'solidBooster:75'
            techTransferMax: 5000
        -   name: 'FlightDataRecorder_Engine'
            flightDataMultiplier: 5
            flightDataEngineerModifier: 0.25
        -   name: 'TestFlightReliability'
            reliabilityCurve:
                - '0 0.001'
                - '10000 0.00005'
        # When referencing a block like this for use in a module, the blocks have to come BEFORE the module itself.  They will then get folded down into it
        -   *ReducedMaxThrust
        -   name: 'TestFlightFailure_ReducedMaxThrust'
            configuration: 'WAC-Corporal'
            weight: 32
            REPAIR:
            - *EasyMechanical
        -   *Explode
        -   name: 'TestFlightFailure_Explode'
            configuration: 'WAC-Corporal'
            weight: 8
    Kickback: &Kickback
        # Should only ever be ONE Interop module for a unique PART in KSP.
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
            techTransfer: 'solidBooster1-1:75'
            techTransferMax: 5000
        -   name: 'FlightDataRecorder_Engine'
            flightDataMultiplier: 5
            flightDataEngineerModifier: 0.25
        -   name: 'TestFlightReliability'
            reliabilityCurve:
                - '0 0.001'
                - '10000 0.00005'
        # When referencing a block like this for use in a module, the blocks have to come BEFORE the module itself.  They will then get folded down into it
        -   *ReducedMaxThrust
        -   name: 'TestFlightFailure_ReducedMaxThrust'
            configuration: 'WAC-Corporal'
            weight: 32
            REPAIR:
            - *EasyMechanical
        -   *Explode
        -   name: 'TestFlightFailure_Explode'
            configuration: 'WAC-Corporal'
            weight: 8
Parts:
-	part: 'RT-5'
	patterns:
	- '@PART[solidBooster_sm]'
	configs:
	- *RT5
-	part: 'RT-10'
	patterns:
	- '@PART[solidBooster]'
	configs:
	- *RT10
-	part: 'BACC'
	patterns:
	- '@PART[solidBooster1-1]'
	configs:
	- *BACC
-	part: 'Kickback'
	patterns:
	- '@PART[MassiveBooster]'
	configs:
	- *Kickback	